/**
 * useInference.ts — loads the alphabet model as TF.js and runs predictions.
 *
 * The TF.js model files must be placed at:
 *   public/models/alphabet/model.json   (generated by tensorflowjs_converter)
 *
 * Predictions are returned as { letter, confidence }.
 * The hook exposes a `predict(features: Float32Array)` function.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import * as tf from "@tensorflow/tfjs";

const ALPHABET_LABELS = "ABCDEFGHIKLMNOPQRSTUVWXY".split("");
const MODEL_URL = "/models/alphabet/model.json";

export type Prediction = {
  letter: string;
  confidence: number;
} | null;

export function useInference() {
  const modelRef = useRef<tf.LayersModel | null>(null);
  const [ready, setReady] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const model = await tf.loadLayersModel(MODEL_URL);
        // Warm up
        const dummy = tf.zeros([1, 63]);
        (model.predict(dummy) as tf.Tensor).dispose();
        dummy.dispose();
        if (cancelled) return;
        modelRef.current = model;
        setReady(true);
      } catch (e) {
        if (!cancelled) {
          console.warn("[Inference] Model not found — sign→text will be unavailable.", e);
          setError("Model not loaded. Run the converter script first.");
        }
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const predict = useCallback((features: Float32Array): Prediction => {
    if (!modelRef.current || !ready) return null;
    return tf.tidy(() => {
      const input = tf.tensor2d([Array.from(features)], [1, 63]);
      const output = modelRef.current!.predict(input) as tf.Tensor;
      const probs = output.dataSync() as Float32Array;
      let maxIdx = 0;
      let maxVal = probs[0];
      for (let i = 1; i < probs.length; i++) {
        if (probs[i] > maxVal) { maxVal = probs[i]; maxIdx = i; }
      }
      return { letter: ALPHABET_LABELS[maxIdx] ?? "?", confidence: maxVal };
    });
  }, [ready]);

  return { ready, error, predict };
}
